


export enum kFunctionType {
    frontend_function = "frontend_function",
    sql_function = "sql_function",
    server_function = "server_function",
    server_global = "server_global",
    frontend_global = "frontend_global",
    // = "//",
    frontend_init_done = "frontend_init_done",
    frontend_closeing = "frontend_closeing",
    frontend_closed = "frontend_closed",

    frontend_init = "frontend_init",
    frontend_viewWasAttached = "frontend_viewWasAttached",
    frontend_react_render = "frontend_react_render",
    frontend_refresh_screen = "frontend_refresh_screen",
    frontend_left_click = "frontend_left_click",
    frontend_hover_in = "frontend_hover_in",
    frontend_hover_out = "frontend_hover_out",
    frontend_hover = "frontend_hover",
    frontend_left_down = "frontend_left_down",
    frontend_left_up = "frontend_left_up",
    frontend_left_dbl_click = "frontend_left_dbl_click",
    frontend_right_down = "frontend_right_down",
    frontend_right_up = "frontend_right_up",
    frontend_right_dbl_click = "frontend_right_dbl_click",
    frontend_mouse_wheel = "frontend_mouse_wheel",
    frontend_key_down = "frontend_key_down",
    frontend_key_up = "frontend_key_up",
    frontend_key_char = "frontend_key_char",
    frontend_syskey_down = "frontend_syskey_down",
    frontend_syskey_up = "frontend_syskey_up",
    frontend_horizontal_scroll = "frontend_horizontal_scroll",
    frontend_vertical_scroll = "frontend_vertical_scroll",
    frontend_context_menu = "frontend_context_menu",
    frontend_move = "frontend_move",
    frontend_resize = "frontend_resize",
    frontend_focus = "frontend_focus",
    frontend_lostfocus = "frontend_lostfocus",
    frontend_drop = "frontend_drop",

    frontend_edit_enter = "frontend_edit_enter",
    frontend_edit_exit = "frontend_edit_exit",
    frontend_edited = "frontend_edited",
}
